Update cargo-generate.toml for leptos template
Fix to be able to run cargo generate for leptos which was throwing me the following error
Error: Substitution skipped, found invalid syntax in
        assets/favicon.ico
        public/favicon.ico